### ISSUE TITLE
执行数据初始化脚本报错，cannot access local variable 'connection' where it is not associated with a value

### ISSUE THREAD

**Issue by wangjiandong-139** [apconw/sanic-web#5]
**问题：**
执行数据初始化脚本报错
RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
....
UnboundLocalError: cannot access local variable 'connection' where it is not associated with a value
**原因：**
缺少必要的包cryptography
**解决方案：**
按照包
pip install cryptography

**Comment by apconw** [comment]
>
